### ISSUE TITLE
Add internal engine `AND` matching condition capability

### ISSUE THREAD

**Issue by naripok** [AirGrid/edgekit#105]
The [EngineCondition](https://github.com/AirGrid/edgekit/blob/fix/%23102/types/index.ts#L133-L139) interface carries an `any` attribute which is not being currently used.
It can be used to add internal engine matching `AND` logic by swapping the evaluation condition on internal [filterPageViews](https://github.com/AirGrid/edgekit/blob/fix/%23102/src/engine/evaluate.ts#L18-L28) method.

**Comment by ydennisy** [comment]
@naripok thanks for this, but closing due to no real need for adding that right now, ideally we should look to simplify the whole engine module.
