### ISSUE TITLE
RFC: Remove pageFeatureGetters API, in favour of direct setting of features.

### ISSUE THREAD

**Issue by ydennisy** [AirGrid/edgekit#57]
## Summary

EdgeKit right now allows the user to pass an `Array` of `pageFeatureGetters` which are objects containing a `name` and `func` key:

```js
const getHtmlKeywords = {
  name: 'keywords',
  func: () => ( return ['kw1', 'kw2'])
};
```

This seems to add a layer of complexity and boilerplate as EdgeKit, then simply executes these functions. For someone wanting to use the project if their function failed it would mean having to try and debug the internals.

- The current API adds boiler
- Adds a layer without any real utility or abstraction
- No real error checking / handling

### Proposal

**Expose a new method which creates a more familiar `set()` based API.**

Rather then providing a list of functions, which resolve to features, we would allow users to set features directly:

```js
edkt.setPageFeatures('keywords', ['kw1', 'kw2']);
```

We could also return a pointer to the feature if for example it needed to be updated:

```js
pageFeaturesPointer = edkt.setPageFeatures('dwell', 20);
// some time passes
pageFeaturesPointer.update('dwell', 30)
```

**Comment by Risto-Stevcev** [comment]
The current implementation for page features does add unnecessary complexity. Some questions I'd have right off the bat is how would this work with:

1. GDPR compliance

For example what happens if GDPR applies but there is no consent, should it return an error or silently fail? etc

2. edkt.run

What happens when this runs before/after edgekit runs?

**Comment by ydennisy** [comment]
That is a good point.

My initial thought was, we allow the user of the lib to set the features but internally we do not set them, we hold them until we know about consent and then decide to set / throw away.

However the issue there is if people are calling APIs, which we are for example there is a cost which we could reduce. Obvious option to solve that would be:
```js
const isConsentGranted = edkt.checkForConsent();

if (isConsentGranted) {
  const features = makeApiCall();
  // the rest of the flow...
}
```
 Do you have some ideas?

On the following:
> edkt.run
> What happens when this runs before/after edgekit runs?

Not very clear what you are referring to here to me - `edkt` is the same thing as running edgekit?

**Comment by Risto-Stevcev** [comment]
Yeah I think exposing `checkForConsent` might be the best route, it might be better to be less opinionated and more flexible for this kind of thing

`edkt.run` needs to be called explicitly right now, takes the page feature getters and audience definitions and runs the engine which stores the page views and matched audiences. How would this fit into that flow? would the user call `edkt.setPageFeatures` before calling `edkt.run`? or would it look different

**Comment by ydennisy** [comment]
Yeah the full flow would end up being:
```js
const isConsentGranted = await edkt.checkForConsent();

if (isConsentGranted) {
  const features = await makeApiCall();
  const audiences = await makeApiCall();
  edkt.setPageFeatures(features);
  edkt.matchAudiences(audiences);
}
```

I am not 100% happy with this:
- I do not like that it has to all go inside of the `if` block.
- I would like to provide a simpler API if possible in addition to a more flexible modular one.

Any ideas for improvment?

**Comment by Risto-Stevcev** [comment]
What about making `setPageFeatures` and `matchAudiences` noop functions if there isn't consent, but also provide a way to disable that behavior if the user wants more explicit control?

**Comment by ydennisy** [comment]
Yeah that can be done, but does it solve the issue described above:
> My initial thought was, we allow the user of the lib to set the features but internally we do not set them, we hold them until 
> we know about consent and then decide to set / throw away.
> However the issue there is if people are calling APIs

**Comment by Risto-Stevcev** [comment]
I was thinking to give the user the ability to disable the behavior for implicit checking so that they have to do it explicitly, but I think that's too verbose.

What about just having the implicit check internally but then also exposing `edkt.checkForConsent` for users if they need more control?

**Comment by ydennisy** [comment]
@Risto-Stevcev please could you provide an example of your suggestion, and ensure its clear that it allows for the stopping of any calls to third party services, when consent is not granted.

**Comment by Risto-Stevcev** [comment]
I was thinking roughly something sort of like this:

```typescript
// hasGdprConsent memoizes the result for any future invocations,
// the promise might already be resolved when called if it was already determined
import { hasGdprConsent } from './gdpr';

// These are all exposed to the user via `edkt.*`:

exports.checkForConsent = hasGdprConsent

exports.setPageFeatures = (...) => {
  if (await hasGdprConsent(vendorIds)) {
    /* Sets the page features _only_ if there's consent */
  }
}

exports.matchAudiences = (...) => {
  if (await hasGdprConsent(vendorIds)) {
    /* Matches and stores audiences _only_ if there's consent */
  }
}
```

That way the simple use-case is available but it's also flexible. For example, the user could use it like this:
```js
const features = await makeApiCall();
const audiences = await makeApiCall();
edkt.setPageFeatures(features);
edkt.matchAudiences(audiences);
```
And it won't set page features or match audiences unless consent is granted.

Or, if the user needs to ensure that they won't make an API call unless consent is granted, they can check as well:

```js
const vendorIds = // ...
if (await edkt.checkForConsent(vendorIds)) {
  const features = await makeApiCall();
  const audiences = await makeApiCall();
  edkt.setPageFeatures(features);
  edkt.matchAudiences(audiences);
}
```

**Comment by ydennisy** [comment]
I cannot tell how this is any different from https://github.com/AirGrid/edgekit/issues/57#issuecomment-698390029

**Comment by Risto-Stevcev** [comment]
The conditional is optional, it will check for consent either way and the library user can add it if they need if for API calls

**Comment by ydennisy** [comment]
Ohh yes ok I got you, that could be better apart from a little opaque if stuff fails due to consent - but we can expose it in config.

One more suggestion and I am not sure if this is better - but it avoids the `if` which I am not a fan off... we could provide users a wrapper function which checks for consent, where they can wrap their API calls, so:

```js
const result = await runOnConsent(makeApiCall);
// if consent true; result is fetched, if consent false result is null
```

**Comment by Risto-Stevcev** [comment]
Ah nice, I like that suggestion more since it avoids the wrapped conditional

**Comment by ydennisy** [comment]
Ok great, I think we can easily make both methods available by:
- exposing the consent check function
- providing a util to "silence" a function call based on consent

**Comment by ydennisy** [comment]
@Risto-Stevcev I think this is good to start work on - some of this is already done as part of the recent work on the GDPR module.

One thing I would suggest we change from what was discussed on this thread is that we should set multiple page features in a single call.

We do not need to for now handle the ability to call it twice, or the ability to update. Lets let the API harden before extending with that sort of functionality.

**Comment by ydennisy** [comment]
Closing this as we set page features direct now.
